#!/bin/bash

cat <<-EOF

Vous pouvez lancer tout module dont vous avez precise le nom
Tapez <return> pour installer les modules, puis encore <return> pour les arreter
EOF

read junk
sudo insmod /usr/realtime/modules/rtai_hal.ko
sudo insmod /usr/realtime/modules/rtai_sched.ko
sudo insmod /usr/realtime/modules/rtai_fifos.ko
sudo insmod 3718.ko
sudo insmod 3712.ko
sudo insmod sensor.ko
sudo insmod controller.ko
sudo insmod $1.ko

lsmod
echo "Le programme fontionne"
echo "Tapez <return> pour l'arreter."
read junk

sudo rmmod $1
sudo rmmod controller
sudo rmmod sensor
sudo rmmod 3712
sudo rmmod 3718
sudo rmmod /usr/realtime/modules/rtai_fifos
sudo rmmod rtai_sched
sudo rmmod rtai_hal
